TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 200
  per_device_train_batch_size: 1
  weight_decay: 0.0
  logging_steps: 10
  eval_strategy: steps
  eval_steps: 500
  save_steps: 1e6
  gradient_accumulation_steps: 4
  dataloader_num_workers: 0
  save_total_limit: 1
  load_best_model_at_end: false