TrainingArguments:
  num_train_epochs: 1
  # ── Quick-run values (dev_run: true in config.yaml) ────────────────────────
  # With dev_subset=40 samples and batch=1 there are only 40 steps per epoch.
  # warmup must be < total steps, eval_steps <= total steps.
  warmup_steps: 5
  per_device_train_batch_size: 1
  weight_decay: 0.0
  logging_steps: 5
  eval_strategy: steps
  eval_steps: 20
  save_steps: 1e6
  gradient_accumulation_steps: 1   # 1 = no accumulation → faster iteration
  dataloader_num_workers: 0
  save_total_limit: 1
  load_best_model_at_end: false